name: roman
channels:
  - conda-forge
  - defaults
  - ska
dependencies:
  - python=3.7
  - tables
  - pip
  - pip:
    - tables
  - numpy
  - pandas
  - tenacity
  - tables
  - sqlalchemy
  - mysql-connector-python
  - mysqlclient
  - astropy 
  - jinja2
  
  
