#!/usr/bin/env python
"""
Contains the Node class definition

Please note that this module is private. The Node class is
available in the main ``wpipe`` namespace - use that instead.
"""
import socket
from .core import datetime, pd, si
from .core import make_yield_session_if_not_cached, make_query_rtn_upd
from .core import initialize_args, wpipe_to_sqlintf_connection, in_session
from .core import split_path
from .proxies import ChildrenProxy

__all__ = ['Node']

KEYID_ATTR = 'node_id'
UNIQ_ATTRS = ['name']
CLASS_LOW = split_path(__file__)[1].lower()


def _in_session(**local_kw):
    return in_session('_%s' % CLASS_LOW, **local_kw)


_check_in_cache = make_yield_session_if_not_cached(KEYID_ATTR, UNIQ_ATTRS, CLASS_LOW)

_query_return_and_update_cached_row = make_query_rtn_upd(CLASS_LOW)


class Node:
    """
        Represents a node of the local machine.

        Call signatures::

            Node(name=socket.gethostname(), int_ip='', ext_ip='')
            Node(keyid)
            Node(_node)

        When __new__ is called, it queries the database for an existing
        row in the `nodes` table via `sqlintf` using the given signature.
        If the row exists, it retrieves its corresponding `sqlintf.Node`
        object, otherwise it creates a new row via a new `sqlintf.Node`
        instance. This `sqlintf.Node` object is then wrapped under the
        hidden attribute `Node._node` in the new instance of this `Node`
        class generated by __new__.

        All nodes are uniquely identified by their name, but alternatively,
        the constructor can take as sole argument either:
         - the primary key id of the corresponding `nodes` table row
         - the `sqlintf.Node` object interfacing that table row

        Parameters
        ----------
        name : string
            Name of node - defaults to socket.gethostname() (see Notes).
        int_ip : string
            Internal IP address of node - defaults to ''.
        ext_ip : string
            External IP address of node - defaults to ''.
        keyid : int
            Primary key id of the table row.
        _node : sqlintf.Node object exposing SQL interface
            Corresponding sqlintf object interfacing the table row.

        Attributes
        ----------
        parents : None
            Dummy attribute with None value.
        name : string
            Name of node.
        node_id : int
            Primary key id of the table row.
        timestamp : datetime.datetime object
            Timestamp of last access to table row.
        int_ip : string
            Internal IP address of node.
        ext_ip : string
            External IP address of node.
        jobs : core.ChildrenProxy object
            List of Job objects owned by node.

        See Also
        --------
        DefaultNode : Node constructed at wpipe importation.

        Notes
        -----
        Importing wpipe constructs a default node stored in DefaultNode. This
        makes use of the socket.gethostname method that returns the current
        host name.
    """
    __cache__ = pd.DataFrame(columns=[KEYID_ATTR]+UNIQ_ATTRS+[CLASS_LOW])

    @classmethod
    def _check_in_cache(cls, kind, loc):
        return _check_in_cache(cls, kind, loc)

    @classmethod
    def _sqlintf_instance_argument(cls):
        if hasattr(cls, '_%s' % CLASS_LOW):
            for _session in cls._check_in_cache(kind='keyid',
                                                loc=getattr(cls, '_%s' % CLASS_LOW).get_id()):
                pass

    def __new__(cls, *args, **kwargs):
        if hasattr(cls, '_inst'):
            old_cls_inst = cls._inst
            delattr(cls, '_inst')
        else:
            old_cls_inst = None
        cls._to_cache = {}
        # checking if given argument is sqlintf object or existing id
        cls._node = args[0] if len(args) else None
        if not isinstance(cls._node, si.Node):
            keyid = kwargs.get('id', cls._node)
            if isinstance(keyid, int):
                for session in cls._check_in_cache(kind='keyid', loc=keyid):
                    cls._node = session.query(si.Node).filter_by(id=keyid).one()
            else:
                # gathering construction arguments
                wpargs, args, kwargs = initialize_args(args, kwargs, nargs=3)
                name = kwargs.get('name', socket.gethostname() if args[0] is None else args[0])
                int_ip = kwargs.get('int_ip', '' if args[1] is None else args[1])
                ext_ip = kwargs.get('ext_ip', '' if args[2] is None else args[2])
                # querying the database for existing row or create
                for session in cls._check_in_cache(kind='args', loc=(name,)):
                    for retry in session.retrying_nested():
                        with retry:
                            this_nested = retry.retry_state.begin_nested()
                            cls._node = this_nested.session.query(si.Node).with_for_update(). \
                                filter_by(name=name).one_or_none()
                            if cls._node is None:
                                cls._node = si.Node(name=name,
                                                    int_ip=int_ip,
                                                    ext_ip=ext_ip)
                                this_nested.session.add(cls._node)
                                this_nested.commit()
                            else:
                                this_nested.rollback()
                            retry.retry_state.commit()
        else:
            cls._sqlintf_instance_argument()
        # verifying if instance already exists and return
        wpipe_to_sqlintf_connection(cls, 'Node')
        # add instance to cache dataframe
        if cls._to_cache:
            cls._to_cache[CLASS_LOW] = cls._inst
            cls.__cache__.loc[len(cls.__cache__)] = cls._to_cache
        new_cls_inst = cls._inst
        delattr(cls, '_inst')
        if old_cls_inst is not None:
            cls._inst = old_cls_inst
        return new_cls_inst

    # @_in_session()
    def __init__(self, *args, **kwargs):
        if not hasattr(self, '_jobs_proxy'):
            self._jobs_proxy = ChildrenProxy(self._node, 'jobs', 'Job',
                                             child_attr='id')
        # self.update_timestamp()

    @classmethod
    def select(cls, *args, **kwargs):
        """
        Returns a list of Node objects fulfilling the kwargs filter.

        Parameters
        ----------
        kwargs
            Refer to :class:`sqlintf.Node` for parameters.

        Returns
        -------
        out : list of Node object
            list of objects fulfilling the kwargs filter.
        """
        with si.begin_session() as session:
            cls._temp = session.query(si.Node).filter_by(**kwargs)
            for arg in args:
                cls._temp = cls._temp.filter(arg)
            return list(map(cls, cls._temp.all()))

    @property
    def parents(self):
        """
        None: Dummy attribute with None value.
        """
        return

    @property
    @_in_session()
    def name(self):
        """
        str: Name of node.
        """
        self._session.refresh(self._node)
        return _query_return_and_update_cached_row(self, 'name')

    @name.setter
    @_in_session()
    def name(self, name):
        self._node.name = name
        _temp = _query_return_and_update_cached_row(self, 'name')
        self.update_timestamp()
        # self._node.timestamp = datetime.datetime.utcnow()
        # self._session.commit()

    @property
    @_in_session()
    def node_id(self):
        """
        int: Primary key id of the table row.
        """
        return self._node.id

    @property
    @_in_session()
    def timestamp(self):
        """
        :obj:`datetime.datetime`: Timestamp of last access to table row.
        """
        self._session.refresh(self._node)
        return self._node.timestamp

    @property
    @_in_session()
    def int_ip(self):
        """
        str: Internal IP address of node.
        """
        return self._node.int_ip

    @property
    @_in_session()
    def ext_ip(self):
        """
        str: External IP address of node.
        """
        return self._node.ext_ip

    @property
    def jobs(self):
        """
        :obj:`core.ChildrenProxy`: List of Job objects owned by node.
        """
        return self._jobs_proxy

    def job(self, *args, **kwargs):
        """
        Returns a job owned by the node.

        Parameters
        ----------
        kwargs
            Refer to :class:`Job` for parameters.

        Returns
        -------
        job : :obj:`Job`
            Job corresponding to given kwargs.
        """
        from .Job import Job
        return Job(self, *args, **kwargs)

    @_in_session()
    def update_timestamp(self):
        """

        """
        self._node.timestamp = datetime.datetime.utcnow()
        self._session.commit()

    def delete(self):
        """
        Delete corresponding row from the database.
        """
        si.delete(self._node)
        self.__class__.__cache__ = self.__cache__[self.__cache__[CLASS_LOW] != self]
